name: Run tests

on:
    push:
    pull_request:

jobs:
    test:
        strategy:
            matrix:
                node: [18.x, 20.x, 22.x]
                os: [ubuntu-22.04]
        runs-on: ${{ matrix.os }}
        # Service containers to run with `container-job`
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install
            - name: Run tests
              run: npm test
